### ISSUE TITLE
Символы > кажутся лишними при создании таблицы.

### ISSUE THREAD

**Issue by Oxotka** [Bayselonarrend/infometrics-articles#1]
Символы > кажутся лишними при создании таблицы.

В markdown они распознаются как цитата.
Без них, на мой взгляд, аккуратнее:

<img width="1264" alt="image" src="https://github.com/Bayselonarrend/infometrics-articles/assets/5194393/37c5409e-649c-4398-bba5-9c1bc61b2c26">

**Comment by Bayselonarrend** [comment]
Ну, на любителя - мне понравилась линия сбоку. Могу как параметр вынести в настройку Action

**Comment by Oxotka** [comment]
Да, это вкусовщина. Тут не спорю.
Еще хотелось бы какую-то минималистичную версию.
Типа только Ссылка и шильдик с реквизитами.

Готов попробовать сделать в отдельной ветке

**Comment by Bayselonarrend** [comment]
Ответил во втором is
