### ISSUE TITLE
Возможно, лучше использовать вместо эмодзи бейджики из GitHub

### ISSUE THREAD

**Issue by Oxotka** [Bayselonarrend/infometrics-articles#2]
Возможно, лучше использовать вместо эмодзи бейджики из GitHub.

Ну то есть вместо таблички 
<img width="487" alt="image" src="https://github.com/Bayselonarrend/infometrics-articles/assets/5194393/61581687-31f3-464b-ac18-d3b24cc3c1e6">

Сделать шильдаками как, например, в OpenYellow.

**Comment by Bayselonarrend** [comment]
Короче сделал новый релиз 1.1 - теперь шаблон можно свой делать
https://github.com/Bayselonarrend/infometrics-articles/releases/tag/1.1
