### ISSUE TITLE
Из-за блока <div id="infostart_posts"> ломается форматирование markdown файла

### ISSUE THREAD

**Issue by Oxotka** [Bayselonarrend/infometrics-articles#3]
Описание:
У меня ридми файл в маркдаун.
Хочу добавить туда вот в таком виде посты:
- Мои публикации на Инфостарт:
     * [Публикация 1](https://infostart.ru) - 50 звезд, 1500 просмотров
     * [Публикация 2](https://infostart.ru) - 51 звезда, 1505 просмотров
     
Из-за того, что присутствует блок `<div id="">` ломается форматирование файла и не получается второй уровень списка.
То есть получается вот так:
- Мои публикации на Инфостарт:
<div id="">
     * [Публикация 1](https://infostart.ru) - 50 звезд, 1500 просмотров
     * [Публикация 2](https://infostart.ru) - 51 звезда, 1505 просмотров
</div>

Вот такой код:
```
- Мои публикации на Инфостарт:
<div id="">
     * [Публикация 1](https://infostart.ru) - 50 звезд, 1500 просмотров
     * [Публикация 2](https://infostart.ru) - 51 звезда, 1505 просмотров
</div>
```

**Comment by Bayselonarrend** [comment]
Теперь нормально должно быть

**Comment by Oxotka** [comment]
При таком исправлении второй уровень вложенности, кажется, не сработает.
То есть публикации будут выглядеть так:
- Мои публикации на Инфостарт:
* [Публикация 1](https://infostart.ru/) - 50 звезд, 1500 просмотров
* [Публикация 2](https://infostart.ru/) - 51 звезда, 1505 просмотров

**Comment by Bayselonarrend** [comment]
С этим я, скорее всего, уже ничего не смогу сделать - в любом случае нужны маркеры начала и конца области для вставки. Даже если они будут не div, а какой-нибудь markdown, уровень вложенности все равно работать не будет

**Comment by Oxotka** [comment]
Да, я понимаю.
Можно, конечно, попробовать чуть усложнить логику шаблона и добавить в параметры еще и заголовок для таблицы. Тогда будет вот такое
```
<div id ="">
[Title]
[Row]
</div>
```

В Title будет идти из параметров
В Row будет идти из шаблона.

Тогда это будет полноценный блок, который можно полностью встроить в страницу.

**Comment by Bayselonarrend** [comment]
Просто вложенные списки - единственная подобная ситуация, когда такое может понадобиться. Да и это обходится html разметкой

```html
<ul>
    <li>
        <p>Статьи на Инфостарт</p>
        <ul>
            <div id="infostart_posts">
            </div>
        </ul>
     </li>
</ul>

```

И в макете

```html
<li><a href="%3">%2</a> - %4 звезд, %8 просмотров</li>
```

**Comment by Oxotka** [comment]
Да, кайф!
