### ISSUE TITLE
Предложение - Собирать не только последние, но и лучшие статьи.

### ISSUE THREAD

**Issue by Oxotka** [Bayselonarrend/infometrics-articles#4]
Предложение - Собирать не только последние, но и лучшие статьи.

Может быть собирать не последние 3, а выбирать 3 лучших за все время.
Мы же тут хвалимся еще.

**Comment by Bayselonarrend** [comment]
Ну, у ИФ никакого API нету, поэтому этот Action просто забирает html страницу профиля и парсит её. А на странице профиля висят 10 последних  ¯\_(ツ)_/¯

**Comment by Oxotka** [comment]
Хмм, вот на этой странице, например, 27 элементов - https://infostart.ru/profile/48967/public/
Вот так можно попробовать отсортировать по топ-рейтинга - https://infostart.ru/profile/237528/public/?sort=property_rating

**Comment by Bayselonarrend** [comment]
Можно взять эту страницу да. Но сейчас парсится страница профиля, надо глянуть, правильно ли она разберется если просто URL поменять

**Comment by BlizD** [comment]
Да, мне тоже кажется надо выводить ТОП из публикаций, а то у меня сейчас показывает просто статьи, а топы вообще не попали =)
https://github.com/BlizD/BlizD

![image](https://github.com/Bayselonarrend/infometrics-articles/assets/10989306/6ce2f32e-003f-47c1-a9ed-af3340e6fcf6)

**Comment by Bayselonarrend** [comment]
Займусь когда разгребусь с OpenIntegrations
